### ISSUE TITLE
Improve data visualization

### ISSUE THREAD

**Issue by mwithi** [informatici/survethi-monitoring-tool#29]
At the moment, if the patient location is known as couple Woreda+Kebele (aka Town+Kebele), it is assigned an RK_CODE (from ArcGIS shapefile) in order to color the related regions' areas on the map. 
If the couple has also a GeoPoint (LOC_LAT, LOC_LONG of the Kebele/s Health Post) a marker is shown.

In the table and in the diseases lists, the latter is now showed as a green (localized) numbers/cells for known GeoPoints, yellow otherwise (not localized).

Aim of this task is to consider a case as "localized" when RK_CODE is available in place of GeoPoint.

Maybe could be advisable to "toggle" GeoPoints showing because are not very meaningful (HealthPost coordinates have been taken as convention up to now).

In any case, still remain to decide what to do for patients where only the Woreda (aka Town) is available, so no RK_CODE nor GeoPoints can be associated with the case (maybe grey color or different hitCount for Woredas and Kebeles?)

**DONE:**
- Oranges show Town + Kebele (_known)
- Greys show Town only (_unknown)
- Blues (on table): Health Post GeoPosition (markers)

**TODO:**
- [x] show greys on the map
- [x] toggle Health Posts layer (replace heatmap)
- [x] add totals badges (in the disease list and main filter)
